### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [flomikoon/BinarySearchTree#1]
По методам `search*`. 
Во-первых, 0 &mdash; может находиться в множестве целых чисел, поэтому возвращать 0 вместо несуществующего элемента некорректно. Во-вторых, ловить `NullPointerException` &mdash; плохой стиль. Можете случайно пропустить какой-нибудь баг. Лучше явно проверить значение на `null`.

**Comment by flomikoon** [comment]
Исправленно
